enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"
excluded-patches = ""
included-patches = ""
version = "latest"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music]
build-mode = "both"
version = "latest"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "both"

[Twitter]
build-mode = "apk"
version = "latest"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
arch = "both"

[Twitch]
enabled = true
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"

[TikTok]
version = "latest"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
arch = "both"

[Reddit]
version = "latest"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[Messenger]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
arch = "arm64-v8a"

[Spotify]
enabled = false
build-mode = "apk"
version = "latest"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[Spotify-Lite]
enabled = false
build-mode = "apk"
version = "latest"
uptodown-dlurl = "https://spotify-lite.en.uptodown.com/android"

[Citra]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/citra-emulator/citra-emulator/"
arch = "arm64-v8a"

[Backdrops]
enabled = false
version = "latest"
uptodown-dlurl = "https://backdrops.en.uptodown.com/android"

[WarnWetter]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/deutscher-wetterdienst/warnwetter/"

[Windyapp]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/windy-weather-world-inc/windy-wind-weather-forecast/"

[MyExpenses]
enabled = true
version = "latest"
uptodown-dlurl = "https://my-expenses.en.uptodown.com/android"

[NyxMusicPlayer]
enabled = false
build-mode = "apk"
version = "latest"
uptodown-dlurl = "https://nyx-music-player.en.uptodown.com/android"

[IconPackStudio]
enabled = false
apkmonk-dlurl = "https://icon-pack-studio.en.uptodown.com/android"
arch = "both"

[TickTick]
enabled = true
version = "latest"
uptodown-dlurl = "https://ticktick.en.uptodown.com/android"
arch = "both"

[Tasker]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/joaomgcd/tasker/"

[Photomath]
enabled = false
apkmonk-dlurl = "https://www.apkmonk.com/app/com.microblink.photomath/"

[Instagram-armeabi-v7a]
enabled = true
version = "latest"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.instagram.android"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
arch = "armeabi-v7a"

[Instagram]
enabled = true
version = "latest"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.instagram.android"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
arch = "arm64-v8a"

[InShorts]
enabled = true
version = "latest"
uptodown-dlurl = "https://inshorts.en.uptodown.com/android"
arch = "both"

[SyncForReddit]
enabled = false
version = "latest"
uptodown-dlurl = "https://sync-for-reddit.en.uptodown.com/android"

[InfinityForReddit]
enabled = true
version = "latest"
uptodown-dlurl = "https://infinity-for-reddit.en.uptodown.com/android"

[Music-Extended]
enabled = true
app-name = "Music"
version = "latest"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "both"

[YouTube-Extended]
enabled = true
app-name = "YouTube"
version = "latest"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
