name: Act on release

on: 
  workflow_call:
    secrets:
      TELEGRAM_TO:
        required: true
      TELEGRAM_TOKEN:
        required: true
    inputs:
      telegram_notification: 
        description: 'Notify on telegram'
        type: boolean
        required: false
        default: false
      release_tag:
        description: 'Release tag'
        type: string
        default: ""
  workflow_dispatch:
    inputs:
      telegram_notification: 
        description: 'Notify on telegram'
        type: boolean
        required: false
        default: false
      release_tag:
        description: 'Release tag'
        type: string
        default: ""
      

jobs:
  Notify_Release:
    name: Notify Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # The python version to use.
          cache: 'pip'
          cache-dependency-path: 'telegram-script/requirements.txt'
        
      - name: Install dependencies
        run: pip install -r telegram-script/requirements.txt
     
      - name: Run telegram notification script
        run: python3 telegram-script


      - name: Edit Release Body
        if: ${{ github.event.inputs.release_tag }}
        run: |
          gh release edit ${{ github.event.inputs.release_tag }} --notes-file release_notification.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Telegram Channel Update
        if: ${{ github.event.inputs.telegram_notification }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message_file: release_notification.md
